### ISSUE TITLE
More info?

### ISSUE THREAD

**Issue by Metaxal** [jeapostrophe/live-free-or-die#2]
Could you provide a little more information about what the consequences of doing this are, in particular in what way this is unsafe?
Does it effectively bypass the transformation of types into contracts?

**Comment by jeapostrophe** [comment]
If you use this in a Client module, then Typed Racket Server modules will not apply contracts to their exports, so you can send them invalid input. Typed Racket internally uses many unsafe things, so now you can crash Typed Racket. Run https://github.com/jeapostrophe/live-free-or-die/blob/master/tests/client-unsafe.rkt and you'll see.

**Comment by Metaxal** [comment]
I see, thanks.
